version: 2.0
jobs:
  build:
    docker:
      - image: circleci/php
    working_directory: ~/impala-php
    steps:
      - checkout
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - restore_cache:
          key: dependency-cache-{{ checksum "composer.json" }}
      - run:
          name: Setup dependencies
          command: composer install
      - save_cache:
          key: dependency-cache-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            ./vendor/bin/phpunit
            ./cc-test-reporter after-build --exit-code $?
workflows:
  version: 2
  build-test:
    jobs:
      - build
